# Generated by Django 5.1.2 on 2024-11-04 12:55

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.GmailValidator]),
        ),
    ]
